### ISSUE TITLE
Python3下异常

### ISSUE THREAD

**Issue by yalechen-cyw3** [WhaleShark-Team/cobra#1291]
### System and Python Environment

|Item|Tooltip|Value|
|---|---|---|
|System|`uname -a`|Darwin XXX-MC2 17.3.0 Darwin Kernel Version 17.3.0: Thu Nov  9 18:09:22 PST 2017; root:xnu-4570.31.3~1/RELEASE_X86_64 x86_64|
|Python|`python -V`|3.7.0|
|Cobra|`python cobra.py`|cobra-v2.0.0-alpha.5|

### Description

![image](https://user-images.githubusercontent.com/34886223/46668181-500d9800-cbfe-11e8-8734-4ff5852009ff.png)

### Steps to Reproduce

1. [First Step]
python cobra.py -t ../source_dir -f json -o ../error_output -d

**Comment by BlBana** [comment]
你是在Python3下打印日志都会抛异常吗，可以详细的说一下你的复现过程吗 ？我这边Python 3.7.0日志都是能正常打印的

**Comment by yalechen-cyw3** [comment]
是的，在Python3下打印日志都会抛异常。

这边也测试了下:

1. 在将输出重定向之后打印日志出现问题：
python cobra.py -t ../source_dir -f json -o ../error_output -d > test.log 2>&1

2. 正常在命令行，不需重定向的场景下，日志能够正常输出：
python cobra.py -t ../source_dir -f json -o ../error_output -d

**Comment by BlBana** [comment]
我这边测试重定向也没有问题：

命令：`python cobra.py -t tests/vulnerabilities/v.java -f json -o ../test.json  -d > test.log 2>&1`

你在Python2下执行这个命令可以正常打印日志吗

**Comment by yalechen-cyw3** [comment]
这边在Python 2.7.10下是可以正常打印日志的。

这边扫描的是PHP代码目录。

**Comment by yalechen-cyw3** [comment]
这边在命令行上是可以正常使用logging库的，之前写的一些代码中的日志打印部分也没有问题。

这里打印输出发现：
python3.7.0下 message确实是bytes类型的，非str类型
在python2下，message为str类型，非unicode类型

**Comment by BlBana** [comment]
![image](https://user-images.githubusercontent.com/22763475/47640018-9ae75380-db9d-11e8-865c-8b3d6ec70f85.png)

我这边打印都是`str`类型，是不是你系统环境的影响呢

**Comment by yalechen-cyw3** [comment]
应该不是，这边在其他的Mac机器下面也是有相同问题。
