### ISSUE TITLE
watch 测试

### ISSUE THREAD

**Issue by 40huo** [WhaleShark-Team/cobra#1296]
### System and Python Environment

|Item|Tooltip|Value|
|---|---|---|
|System|`uname -a`||
|Python|`python -V`||
|Cobra|`python cobra.py`||

### Description

[Description of the bug or feature]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

**Comment by BlBana** [comment]
test

**Comment by BlBana** [comment]
test

**Comment by 40huo** [comment]
2222
