### ISSUE TITLE
扫描任务长时间不结束

### ISSUE THREAD

**Issue by arthur657834** [WhaleShark-Team/cobra#1327]
### System and Python Environment

|Item|Tooltip|Value|
|---|---|---|
|System|`uname -a`||

Linux qa-cemon-pro 3.10.0-327.el7.x86_64 #1 SMP Thu Nov 19 22:10:57 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

|Python|`python -V`||

Python 2.7.5

|Cobra|`python cobra.py`||

### Description

[xxx@qa-cemon-pro cobra]$ more /tmp/cobra/running/adb439oes9x5_status 
{"status": "running", "report": "?sid=adb439oes9x5"}
[xxxx@qa-cemon-pro cobra]$ ll /tmp/cobra/running/adb439oes9x5_status     
-rw-r--r-- 1 root root 52 Nov 21 17:03 /tmp/cobra/running/adb439oes9x5_status

已经5天了！！！

接口查询数据返回:

{
    "code": 1001,
    "result": {
        "status": "running",
        "report": "http://10.1.14.209:8888/?sid=adb439oes9x5",
        "allow_deploy": true,
        "sid": "adb439oes9x5",
        "msg": "success",
        "still_running": {
            "sdb439cmo1qx": "https://gitlab.xxxx.com/tool-backend/custom/customservice.git:feature/CMP-4"
        },
        "total_target_num": 1,
        "not_finished": 1,
        "statistic": {
            "high": 0,
            "medium": 0,
            "critical": 0,
            "low": 0
        }
    }
}

[Description of the bug or feature]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

**Comment by BlBana** [comment]
进程应该是卡死了，你扫的是什么项目呢，PHP还是Java呢

**Comment by arthur657834** [comment]
java

**Comment by BlBana** [comment]
使用的什么分支扫描的呢，master分支还是Cobra-Java分支呢

**Comment by arthur657834** [comment]
master

**Comment by BlBana** [comment]
能不能把卡死部分的日志发出来看看呢

**Comment by arthur657834** [comment]
日志路径？

**Comment by BlBana** [comment]
Cobra/logs目录下

**Comment by arthur657834** [comment]
[xxxx@qa-cemon-pro cobra]$ more running/a04c90vmcjk6_status 
{"status": "running", "report": "?sid=a04c90vmcjk6"}
[xxxx@qa-cemon-pro cobra]$ more running/a04c90vmcjk6_list 
{"sids": {"s04c90twhz0k": "xxxxxx"}, "total_target_num": 1}
