### ISSUE TITLE
web模式下  target字段不支持 文件目录路径？ 之前都可以 现在只能是http的git地址?

### ISSUE THREAD

**Issue by menglike** [WhaleShark-Team/cobra#1340]
### System and Python Environment

|Item|Tooltip|Value|
|---|---|---|
|System|`uname -a`||
|Python|`python -V`||
|Cobra|`python cobra.py`||

### Description

[Description of the bug or feature]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

**Comment by BlBana** [comment]
是的，现在取消了Web模式下对文件目录的支持，如果有这个需求的话可以参照 #1242 commit删除相应代码，但是会造成文件读取漏洞
