### ISSUE TITLE
代码上传可以扫描但是 URL直接请求扫描不行请问要如何解决这个问题

### ISSUE THREAD

**Issue by Mr89898** [WhaleShark-Team/cobra#1346]

**Comment by BlBana** [comment]
有没有具体报错信息，或者日志呢

**Comment by Mr89898** [comment]
没有报错，扫描的时候直接跳到未发现漏洞页面

**Comment by BlBana** [comment]
可以在终端看看你的日志信息，会有打印

**Comment by Mr89898** [comment]
也没有打印

**Comment by Mr89898** [comment]
很奇怪

**Comment by BlBana** [comment]
什么提示信息都没有吗 ？

**Comment by Mr89898** [comment]
> 什么提示信息都没有吗？

没有报错的提示，

**Comment by BlBana** [comment]
把你Web界面和终端截图给我看看吧

**Comment by Mr89898** [comment]
> 把你的Web界面和终端截图给我看看吧
![image](https://user-images.githubusercontent.com/24852223/50146418-9f530180-02ee-11e9-8718-50e8b14509af.png)

![image](https://user-images.githubusercontent.com/24852223/50146482-c8739200-02ee-11e9-94c2-01e3d0a95004.png)

**Comment by BlBana** [comment]
你的git地址不是.git结尾吧，你把URL写完整
http://github.com/xxx/xxx.git试试

**Comment by Mr89898** [comment]
> 你的git的地址不是git的结尾吧，你把URL完整写
> [http://github.com/xxx/xxx.git试试](https://github.com/xxx/xxx.git%E8%AF%95%E8%AF%95)

是GIT的结尾

**Comment by BlBana** [comment]
应该是git拉取的问题，代码没有成功拉下来，你调试一下看看是哪里出了问题

**Comment by Mr89898** [comment]
> 应该是GIT中拉取的问题，代码没有成功拉下来，你调试一下看看是哪里出了问题

调试发现请求都是正常的所以不知道是哪里出的问题

**Comment by Mr89898** [comment]
> > 应该是GIT中拉取的问题，代码没有成功拉下来，你调试一下看看是哪里出了问题
> 
> 调试发现请求都是正常的所以不知道是哪里出的问题

是否方便加个好友请教一下

**Comment by Mr89898** [comment]
> > > 应该是GIT中拉取的问题，代码没有成功拉下来，你调试一下看看是哪里出了问题
> > 
> > 
> > 调试发现请求都是正常的所以不知道是哪里出的问题
> 
> 是否方便加个好友请教一下

是需要有EXP才能扫描吗

**Comment by BlBana** [comment]
你要是拉自己搭建的库，就需要配置gitlab的账号密码

**Comment by Mr89898** [comment]
> 你要是拉自己搭建的库，就需要配置gitlab的账号密码

gitlab的账号密码也有配置，就是PULL不下来

**Comment by BlBana** [comment]
你打印一下pickup.py里面，你拉取的git地址，看看是否带有你的账号密码

**Comment by Mr89898** [comment]
> pickup.py

怎么操作

**Comment by BlBana** [comment]
pickup.py的399行打印clone_address看看

**Comment by Mr89898** [comment]
> > pickup.py的399行打印clone_address看看
> 
> ![image](https://user-images.githubusercontent.com/24852223/50202714-ef3ad280-0399-11e9-89f3-d76df4d2a651.png)
![image](https://user-images.githubusercontent.com/24852223/50203022-1514a700-039b-11e9-81a8-8dd2a59eb912.png)
报错提示这个 我根据网上的init git后还是不行，进入目录后发现./git目录存在但是用ls和pwd看不到是否跟隐藏了有关系

**Comment by Mr89898** [comment]
> > pickup.py的399行打印clone_address看看
> 
> ![image](https://user-images.githubusercontent.com/24852223/50202714-ef3ad280-0399-11e9-89f3-d76df4d2a651.png)
![image](https://user-images.githubusercontent.com/24852223/50203131-6e7cd600-039b-11e9-81a0-5a61601db7a4.png)
报错信息是这个我根据网上说的 init git了但是还是不行

**Comment by Mr89898** [comment]
现在确实不知道问题出在哪里了

**Comment by BlBana** [comment]
我是说在399行以下，加入代码
`print(clone_address)`
然后终端看看打印出来的Git地址是不是带上了你的git账号密码

**Comment by Mr89898** [comment]
> 我是说在399行以下，加入代码
> `print(clone_address)`
> 然后终端看看打印出来的Git地址是不是带上了你的git账号密码

我应该怎么做

**Comment by Mr89898** [comment]
> > 我是说在399行以下，加入代码
> > `print(clone_address)`
> > 然后终端看看打印出来的Git地址是不是带上了你的git账号密码
> 
> 我应该怎么做

请问终端打印要怎么操作
