### ISSUE TITLE
CENTOS下运行时出现错误,

### ISSUE THREAD

**Issue by Mr89898** [WhaleShark-Team/cobra#1348]
### System and Python Environment

|Item|Tooltip|Value|
|---|---|---|
|System|`uname -a`||
|Python|`python -V`||
|Cobra|`python cobra.py`||

### Description

[Description of the bug or feature]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]
![image](https://user-images.githubusercontent.com/24852223/50270550-dfd88980-046c-11e9-980c-69a603d0da93.png)

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

**Comment by BlBana** [comment]
安装cloghandler类库
