### ISSUE TITLE
扫描第一次时可以扫描，扫描第二次时就不行了

### ISSUE THREAD

**Issue by Mr89898** [WhaleShark-Team/cobra#1350]
### System and Python Environment

|Item|Tooltip|Value|
|---|---|---|
|System|`uname -a`||
|Python|`python -V`||
|Cobra|`python cobra.py`||

### Description

[Description of the bug or feature]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

**Comment by BlBana** [comment]
什么意思 ？第二次会怎么样

**Comment by Mr89898** [comment]
之前有扫描过一次第一次扫描成功。第二次同一个GIT扫描会直接跳到没有检测到漏洞的界面，日志文件显示已存在分支，GIT存储库已存在，无法把代码库PULL下来

**Comment by BlBana** [comment]
你是说git pull 操作给失败了吗 ？有具体报错信息吗

**Comment by Mr89898** [comment]
> 你是说git pull 操作给失败了吗 ？有具体报错信息吗

有
![image](https://user-images.githubusercontent.com/24852223/50328659-eb8c8480-052e-11e9-8582-fd4383b8e334.png)

**Comment by Mr89898** [comment]
> 你是说git pull 操作给失败了吗 ？有具体报错信息吗

我把git init了也是不行的不知道是哪里的问题

**Comment by BlBana** [comment]
这个问题出在pickup.py文件的455行——486行之间，可以调试一下对应代码来排查一下问题，你给的信息我定位不到具体的问题点
