### ISSUE TITLE
Dockerfile文件裡面ubuntu:xenial鏡像在哪兒

### ISSUE THREAD

**Issue by liujunfei980** [WhaleShark-Team/cobra#1352]
我將項目克隆下來后，通過裡面的Dockerfile文件build鏡像，提示找不到ubuntu:xenial基礎鏡像，這個鏡像是你自己製作的還是使用docker倉庫的ubuntu鏡像？

**Comment by BlBana** [comment]
![image](https://user-images.githubusercontent.com/22763475/51956943-8e1c1980-2484-11e9-933b-7147698c58a7.png)

![image](https://user-images.githubusercontent.com/22763475/51956952-9c6a3580-2484-11e9-8b36-a8ec41d8e6ef.png)

你好，这个镜像是官方提供的镜像，你可以确认一下Dockerfile是否出错
