### ISSUE TITLE
邮箱报告

### ISSUE THREAD

**Issue by pinganye219** [WhaleShark-Team/cobra#1355]
你好，咨询一下Cobra后台如何访问？
生成PDF文档可以么？如何发给指定邮箱？比如发给jzw851029@163.com这个邮箱，config文件该如何配置

**Comment by BlBana** [comment]
Cobra只有一个报告界面，没有后台的

目前支持XML,CSV,JSON格式的导出，不支持PDF文档

发送邮箱的话可以在`config`文件当中，配置好`host, port, username, password, sender, ssl`几个参数以后就可以给指定的邮箱发送结果邮件
