### ISSUE TITLE
关于使用方面的问题

### ISSUE THREAD

**Issue by yuynagforhacker** [WhaleShark-Team/cobra#1356]
请教：
首先是report页面，如何清除之前所扫描的缓存？
其次是github首页中的截图，怎么才能展示出漏洞页面？
然后是扫描后如何查看SID？全部任务或某个任务的SID
以上.

**Comment by BlBana** [comment]
1. Cobra的结果数据都是以文件的形式进行存储的，可以清空 **/tmp/cobra/running** 文件来清楚之前扫描过的缓存

2. 漏洞页面可以启动Cobra API的检测模式，启动命令：
```bash
python cobra.py -H 127.0.0.1 -P 80
```

3. 在使用CLI和API模式检测时，都会返回一个**a**开通的字符串，为整个扫描任务的SID，通过这个SID在 **/tmp/cobra/running** 目录下查看 **SID_list**可以获取整个扫描任务中，单个扫描项目的SID

**Comment by yuynagforhacker** [comment]
多谢指导，同时有个问题，在此提出一个假设，我看了/tmp/cobra/running目录下的文件，都是以乱序随机命名的，不能直观的观察出我扫描的对象以及SID，需要进行全局搜索对象才可以确定SID进行查询。但与此同时，我不能清晰的查看我的扫描历史记录，造成任务重复资源浪费，这一点可否改进一下？
