### ISSUE TITLE
GUI使用方面的问题

### ISSUE THREAD

**Issue by 13622609289** [WhaleShark-Team/cobra#1357]
python cobra.py -H 127.0.0.1 -P 8888运行后
浏览器访问127.0.0.1:8888页面，Ex:http://github.com/FeeiCN/grw.git or /home/Feei/project_name输入框提示可以输入本地路径，为何输入后/home/project_name后却提示：Please input a valid URL，查看源码，好像现在只支持git路径，建议把本地扫码也能支持，不然每次只能用CLI模式扫码完后在通过?sid=ace8bcsxst3n得到图形结果比较麻烦

**Comment by BlBana** [comment]
之前本来支持本地路径检测的，但是这样子会存在文件泄露的问题，之后就关闭了这个功能

**Comment by 13622609289** [comment]
> 之前本来支持本地路径检测的，但是这样子会存在文件泄露的问题，之后就关闭了这个功能

能否自行开启该功能？

**Comment by BlBana** [comment]
可以把那条检测项目地址是否为URL的正则去掉，但是这样要注意可能存在文件泄露的情况

**Comment by 13622609289** [comment]
> 可以把那条检测项目地址是否为URL的正则去掉，但是这样要注意可能存在文件泄露的情况

好的，非常感谢
