### ISSUE TITLE
关于自动生成parsetab.py文件问题

### ISSUE THREAD

**Issue by 13622609289** [WhaleShark-Team/cobra#1358]
能否扫描完成而不自动生成parsetab.py此文件，因为实际开发中每次提交代码前扫描完后，提交代码时把该文件也一同提交上去了。

**Comment by BlBana** [comment]
`parsetab.py`是什么文件呢，Cobra不会生成这个文件的

**Comment by 13622609289** [comment]
> `parsetab.py`是什么文件呢，Cobra不会生成这个文件的

# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = 'leftINCLUDEI.......................

文件前几行大概是这样的

**Comment by BlBana** [comment]
测试不会生成这个文件呢，可以把这个文件添加到`.gitignore`文件中去，忽略提交

**Comment by 13622609289** [comment]
> 测试不会生成这个文件呢，可以把这个文件添加到`.gitignore`文件中去，忽略提交

找到原因了，是因为cobra程序根目录缺少parsetab.py这个文件的话就会自动在扫描目录生成的，把生成的文件拷贝过去下次就不会生成了
