### ISSUE TITLE
使用文档中的一些疑问

### ISSUE THREAD

**Issue by 13622609289** [WhaleShark-Team/cobra#1361]
http://cobra.feei.cn/languages
这里提到的支持语言
主语言：是、否是什么意思？

**Comment by grayguest** [comment]
应该是指主要支持的语言的意思。

**Comment by BlBana** [comment]
这里指Cobra可以检测的语言类型
PHP，Java两种语言现在已经支持了AST的语法树分析检测
其他的语言目前只支持正则检测，可以根据自己的需求编写规则

**Comment by nanshihui** [comment]
master 是不是还没有集成 java ast？

**Comment by BlBana** [comment]
对的，现在master分支还没有合并上Java-ast的检测功能，在Cobra-Java分支上可以使用Java检测，PHP也支持，等测试稳定的时候会把Java分析功能合并到master分支上
