### ISSUE TITLE
match规则模式regex-param-controllable应该不支持java吧

### ISSUE THREAD

**Issue by grayguest** [WhaleShark-Team/cobra#1362]
作者师傅们你们好，最近在学习cobra的代码，非常感谢无私奉献，有一些疑惑还望指点。
http://cobra.feei.cn/rule_template 文档里面写了支持php/java，实际代码中
https://github.com/WhaleShark-Team/cobra/blob/master/cobra/engine.py#L648
其实只判断了php，没有判断java。
最后，有cobra交流群吗？请求加入，扣扣 9614六2392

**Comment by BlBana** [comment]
关于Java的参数AST已经可以支持了，可以切换到Cobra-Java分支进行使用，在engine.py中已经加入了对Java代码的判断，后续会完善相应的文档
