### ISSUE TITLE
parser.py中get_binaryop_params()函数逻辑问题

### ISSUE THREAD

**Issue by grayguest** [WhaleShark-Team/cobra#1363]
作者师傅们你们好，最近在学习cobra的代码，非常感谢无私奉献，有一些疑惑还望指点。
https://github.com/WhaleShark-Team/cobra/blob/master/cobra/parser.py#L142
这句代码应该可以去掉？参考下图。
![A3QwCD.png](https://s2.ax1x.com/2019/03/21/A3QwCD.png)
最后，有cobra交流群吗？请求加入，扣扣 9614六2392

**Comment by BlBana** [comment]
这句代码是为了将 二元表达式 中加号左右部分的参数进行合并操作，所以不能去掉的

**Comment by BlBana** [comment]
**578732936** 为Cobra交流群，可以加入一起探讨问题

**Comment by grayguest** [comment]
> 这句代码是为了将 二元表达式 中加号左右部分的参数进行合并操作，所以不能去掉的

但是params_right和params_left都是params的引用，实际上这3者的值都是一样的，在执行完get_binaryop_deep_params(node.left, params)之后，师傅可以跟踪调试一下。

**Comment by grayguest** [comment]
师傅仔细看一下我的图片，我是一步一步跟踪调试的。

**Comment by BlBana** [comment]
好的，我这边调试一下试试
