### ISSUE TITLE
engine.py中parser失败后是否应该继续往下执行？

### ISSUE THREAD

**Issue by grayguest** [WhaleShark-Team/cobra#1364]
https://github.com/WhaleShark-Team/cobra/blob/master/cobra/engine.py#L677
如果触发了Parser failed，为什么还要往下继续执行呢？下面的逻辑应该是针对Regex-Param-Controllable的吧？
如果继续往下执行，跟进一下 ast.is_controllable_param()函数发现ast.is_controllable_param()函数里面的param_name会是函数名称，而不是string或者variable。

**Comment by grayguest** [comment]
我好像明白了，如果是Function-Param-Controllable成功，也是需要执行match2和repair判断的，如果是Regex-Param-Controllable，多出来的是这一步param_is_controllable, data = ast.is_controllable_param()，如果失败了，也不会影响，但是这样也会多执行下面的呀，要不要考虑对条件判断优化一下？

**Comment by grayguest** [comment]
如果Function-Param-Controllable失败，ast.is_controllable_param()永远都是无用的执行逻辑，match2和repair应该也没用了吧，因为都已经失败了，不需要再进行match2或者repair的匹配了吧？

**Comment by BlBana** [comment]
是的，这是两种检测逻辑，下面的ast.is_controllable_param()主要是使用正则的方式对代码进行分析，这是最初Cobra采用的AST分析模式，而parser使用语法树分析的方式对代码进行了检测，在parser分析结束以后可以不再使用ast.is_controllable_param()检测逻辑
