### ISSUE TITLE
请问gitlab怎么配置啊

### ISSUE THREAD

**Issue by tianguozhifeng** [WhaleShark-Team/cobra#1368]
如图所示，我配置了账户、密码和id，还需要 配置什么啊

![ZCV 7WQ{3N0BVSM@7 9@O1I](https://user-images.githubusercontent.com/25656581/56873388-97595a00-6a64-11e9-9390-c08298c30884.png)

**Comment by BlBana** [comment]
1. 如果是单个扫描gitlab的项目只需要配置好 **username** 和 **password**
2. 如果全量扫描gitlab上的项目,需要配置好 **private_token** 和  **gitlab_url**

**Comment by tianguozhifeng** [comment]
![image](https://user-images.githubusercontent.com/25656581/57187915-b5253400-6f28-11e9-947f-a8e04ddbe389.png)

如上图所示，已经配置了private_token和url，但日志一直显示在 INFO [399] [PICKUP] [CLONE] clone repository...
