### ISSUE TITLE
CLI模式下，扫描文件夹下的代码；卡住了；

### ISSUE THREAD

**Issue by tanghulu9312** [WhaleShark-Team/cobra#1369]
CLI模式下，扫描文件夹下的代码；卡住了；打印信息：[CRITICAL] [AST] line exception:0;这段打印信息的背景是红色

**Comment by BlBana** [comment]
有没有具体的报错信息呢，可以截图放上来

**Comment by tanghulu9312** [comment]
> 有没有具体的报错信息呢，可以截图放上来

解决了，配置文件文件的问题
