### ISSUE TITLE
gitlab配置还是存在问题

### ISSUE THREAD

**Issue by tianguozhifeng** [WhaleShark-Team/cobra#1371]
![image](https://user-images.githubusercontent.com/25656581/57188203-4b5b5900-6f2d-11e9-9263-ca013d32d112.png)

如图所示配置，然后一直卡在下面复制仓库了

![image](https://user-images.githubusercontent.com/25656581/57188214-72198f80-6f2d-11e9-95af-fd6c2cee1725.png)

能留个联系方式吗，谢谢哈

**Comment by BlBana** [comment]
https://github.com/WhaleShark-Team/cobra/blob/7835a0cf4c696d61b71552b046374277d05bf144/cobra/pickup.py#L406-L417

可以看看这块代码，`print(clone_address)` 参数，检查一下自己的项目地址以及 `username` 和 `password` 信息是否正确；如果没有问题的话，可能是项目代码过大，正在拉取代码当中，可以等等是否出现报错信息

我的邮箱: `blbana@qq.com`
