### ISSUE TITLE
如何结合nginx+uwsgi来部署cobra；项目入口文件是哪一个呢？

### ISSUE THREAD

**Issue by tanghulu9312** [WhaleShark-Team/cobra#1372]
如何结合nginx+uwsgi来部署cobra；项目入口文件是哪一个呢？

**Comment by BlBana** [comment]
CLI模式和API模式的启动方式都是根目录下的cobra.py文件，根据不同的参数启动相应的模式

结合nging + uwsgi可以在cobra/api.py文件中获取到Flask的application，结合uwsgi进行部署


BlBana
blbana@qq.com
 
发件人： tanghulu9312
发送时间： 2019-05-05 15:39
收件人： WhaleShark-Team/cobra
抄送： Subscribed
主题： [WhaleShark-Team/cobra] 如何结合nginx+uwsgi来部署cobra；项目入口文件是哪一个呢？ (#1372)
如何结合nginx+uwsgi来部署cobra；项目入口文件是哪一个呢？
