### ISSUE TITLE
信息泄露的误报

### ISSUE THREAD

**Issue by yichinzhu** [WhaleShark-Team/cobra#768]
### System and Python Environment

|Item|Tooltip|Value|
|---|---|---|
|Python|`python -V`|2.7|
|Cobra|`python cobra.py`|latest|

### Description

如下php代码
```php
<?php
$a = "this is a variable";
//var_dump($a);
echo 2333;
?>
```
被检测出var_dump信息泄露，实际上var_dump是已经注释掉的代码
### 误报原因

CVI-190009.xml中信息泄露的匹配模式是`regex-only-math`，而在engine.py line 520-537中
```python
    def is_annotation(self):
        match_result = re.findall(r"^(#|\\\*|\/\/)+", self.code_content)
        # Skip detection only on match
        if self.is_match_only_rule():
            return False
        else:
            return len(match_result) > 0
```
如果是仅正则匹配就不进行注释判断导致了误报

p.s. 注释符`/*`错写成了`\*`

感觉这段的作用不是很大（没仔细研究，不负责任的推断），如果判断模式是function-param-controllable，注释部分在语法分析后就会自动去除，最后返回FUNCTION-PARAM-CONTROLLABLE，如果是regex-only模式，这里又不进行注释匹配。

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

**Comment by BlBana** [comment]
这么写是为了提示开发人员注释代码中存在漏洞，避免去掉注释符以后产生漏洞，现在已经优化了这种漏洞出现时的提示内容

**Comment by yichinzhu** [comment]
@BlBana `re.findall(r"^(#|\\\*|\/\/)+", self.code_content)` 应该为 `re.findall(r"^(#|\/\*|\/\/)+", self.code_content)`吧

**Comment by BlBana** [comment]
对，代码已经改过了现在还没有合并上来
